# Generated by Django 2.2.7 on 2019-11-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackapp', '0005_auto_20191109_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
