# Generated by Django 2.2.7 on 2019-11-09 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackapp', '0006_auto_20191109_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='inherit',
            new_name='post',
        ),
    ]
