# Generated by Django 2.2.7 on 2019-11-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackapp', '0007_auto_20191109_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='imges/'),
        ),
    ]
