# Generated by Django 2.2.7 on 2019-11-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackapp', '0008_auto_20191109_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
