# Generated by Django 2.2.7 on 2019-11-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackapp', '0009_challenge_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='number',
        ),
        migrations.AlterField(
            model_name='challenge',
            name='image',
            field=models.ImageField(null=True, upload_to='imges/'),
        ),
    ]
