# Generated by Django 2.2.7 on 2019-11-09 16:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hackapp', '0010_auto_20191110_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='likes',
            field=models.ManyToManyField(related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
