# Generated by Django 2.2.7 on 2019-11-09 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackapp', '0011_challenge_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenge',
            options={'ordering': ['id']},
        ),
    ]
