# Generated by Django 2.2.7 on 2019-11-09 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackapp', '0012_auto_20191110_0234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenge',
            options={},
        ),
    ]
